// Generated by tools/build-art.mjs from reviewed source manifests.
export const CARD_ART={
  "CN01": {
    "path": "assets/players/CN01.jpg",
    "profileUrl": "https://www.vlr.gg/player/49973/glacier",
    "name": "glacier",
    "kind": "photo",
    "photoPage": "https://www.sina.cn/news/detail/5282469844877859.html",
    "photoCredit": "狼队电竞无畏契约分部 · glacier 官宣",
    "fit": "cover"
  },
  "CN02": {
    "path": "assets/players/CN02.png",
    "profileUrl": "https://www.vlr.gg/player/31753/spiritz1",
    "name": "SpiritZ1",
    "kind": "photo"
  },
  "CN03": {
    "path": "assets/players/CN03.png",
    "profileUrl": "https://www.vlr.gg/player/37494/kai",
    "name": "Kai",
    "kind": "photo"
  },
  "CN04": {
    "path": "assets/players/CN04.png",
    "profileUrl": "https://www.vlr.gg/player/3028/life",
    "name": "Life",
    "kind": "photo"
  },
  "CN05": {
    "path": "assets/players/CN05.png",
    "profileUrl": "https://www.vlr.gg/player/22047/rarga",
    "name": "Rarga",
    "kind": "photo"
  },
  "CN06": {
    "path": "assets/players/CN06.png",
    "profileUrl": "https://www.vlr.gg/player/3520/zmjjkk",
    "name": "ZmjjKK",
    "kind": "photo"
  },
  "CN07": {
    "path": "assets/players/CN07.png",
    "profileUrl": "https://www.vlr.gg/player/6022/yosemite",
    "name": "yosemite",
    "kind": "photo"
  },
  "CN08": {
    "path": "assets/players/CN08.png",
    "profileUrl": "https://www.vlr.gg/player/11218/yuicaw",
    "name": "Yuicaw",
    "kind": "photo"
  },
  "CN09": {
    "path": "assets/players/CN09.png",
    "profileUrl": "https://www.vlr.gg/player/3741/vo0kashu",
    "name": "vo0kashu",
    "kind": "photo"
  },
  "CN10": {
    "path": "assets/players/CN10.png",
    "profileUrl": "https://www.vlr.gg/player/47629/coco",
    "name": "Coco",
    "kind": "photo"
  },
  "CN11": {
    "path": "assets/players/CN11.png",
    "profileUrl": "https://www.vlr.gg/player/3045/luok1ng",
    "name": "LuoK1ng",
    "kind": "photo"
  },
  "CN12": {
    "path": "assets/players/CN12.png",
    "profileUrl": "https://www.vlr.gg/player/4742/smoggy",
    "name": "Smoggy",
    "kind": "photo"
  },
  "CN13": {
    "path": "assets/players/CN13.png",
    "profileUrl": "https://www.vlr.gg/player/7857/berlin",
    "name": "BerLIN",
    "kind": "photo"
  },
  "CN14": {
    "path": "assets/players/CN14.png",
    "profileUrl": "https://www.vlr.gg/player/3017/nobody",
    "name": "nobody",
    "kind": "photo"
  },
  "CN15": {
    "path": "assets/players/CN15.png",
    "profileUrl": "https://www.vlr.gg/player/7849/siufatbb",
    "name": "SiuFatBB",
    "kind": "photo"
  },
  "CN16": {
    "path": "assets/players/CN16.png",
    "profileUrl": "https://www.vlr.gg/player/15559/chichoo",
    "name": "CHICHOO",
    "kind": "photo"
  },
  "CN17": {
    "path": "assets/players/CN17.png",
    "profileUrl": "https://www.vlr.gg/player/4720/haodong",
    "name": "Haodong",
    "kind": "photo"
  },
  "CN18": {
    "path": "assets/players/CN18.png",
    "profileUrl": "https://www.vlr.gg/player/19530/aaaay",
    "name": "AAAAY",
    "kind": "photo"
  },
  "ST01": {
    "path": "assets/special/ST01.svg",
    "name": "信息干扰",
    "kind": "illustration"
  },
  "ST02": {
    "path": "assets/special/ST02.svg",
    "name": "节奏受阻",
    "kind": "illustration"
  },
  "ST03": {
    "path": "assets/special/ST03.svg",
    "name": "疲劳",
    "kind": "illustration"
  },
  "CU01": {
    "path": "assets/special/CU01.svg",
    "name": "磨合不足",
    "kind": "illustration"
  },
  "CU02": {
    "path": "assets/special/CU02.svg",
    "name": "舆论压力",
    "kind": "illustration"
  },
  "TK01": {
    "path": "assets/special/TK01.svg",
    "name": "补枪",
    "kind": "illustration"
  },
  "TK02": {
    "path": "assets/special/TK02.svg",
    "name": "临时部署",
    "kind": "illustration"
  },
  "AM01": {
    "path": "assets/players/AM01.png",
    "profileUrl": "https://www.vlr.gg/player/601/asuna",
    "name": "Asuna",
    "kind": "photo"
  },
  "AM02": {
    "path": "assets/players/AM02.png",
    "profileUrl": "https://www.vlr.gg/player/18796/oxy",
    "name": "OXY",
    "kind": "photo"
  },
  "AM03": {
    "path": "assets/players/AM03.png",
    "profileUrl": "https://www.vlr.gg/player/8480/aspas",
    "name": "aspas",
    "kind": "photo"
  },
  "AM04": {
    "path": "assets/players/AM04.png",
    "profileUrl": "https://www.vlr.gg/player/4004/zekken",
    "name": "zekken",
    "kind": "photo"
  },
  "AM05": {
    "path": "assets/players/AM05.png",
    "profileUrl": "https://www.vlr.gg/player/8673/heat",
    "name": "heat",
    "kind": "photo"
  },
  "AM06": {
    "path": "assets/players/AM06.png",
    "profileUrl": "https://www.vlr.gg/player/3722/koalanoob",
    "name": "koalanoob",
    "kind": "photo"
  },
  "AM07": {
    "path": "assets/players/AM07.png",
    "profileUrl": "https://www.vlr.gg/player/4147/cryocells",
    "name": "Cryocells",
    "kind": "photo"
  },
  "AM08": {
    "path": "assets/players/AM08.png",
    "profileUrl": "https://www.vlr.gg/player/1818/tex",
    "name": "tex",
    "kind": "photo"
  },
  "AM09": {
    "path": "assets/players/AM09.png",
    "profileUrl": "https://www.vlr.gg/player/2170/babybay",
    "name": "BABYBAY",
    "kind": "photo"
  },
  "AM10": {
    "path": "assets/players/AM10.png",
    "profileUrl": "https://www.vlr.gg/player/3880/bang",
    "name": "bang",
    "kind": "photo"
  },
  "AM11": {
    "path": "assets/players/AM11.png",
    "profileUrl": "https://www.vlr.gg/player/17433/v1c",
    "name": "v1c",
    "kind": "photo"
  },
  "AM12": {
    "path": "assets/players/AM12.png",
    "profileUrl": "https://www.vlr.gg/player/8549/kingg",
    "name": "kiNgg",
    "kind": "photo"
  },
  "AM13": {
    "path": "assets/players/AM13.png",
    "profileUrl": "https://www.vlr.gg/player/20140/vora",
    "name": "vora",
    "kind": "photo"
  },
  "AM14": {
    "path": "assets/players/AM14.png",
    "profileUrl": "https://www.vlr.gg/player/10885/davih",
    "name": "DaviH",
    "kind": "photo"
  },
  "AM15": {
    "path": "assets/players/AM15.png",
    "profileUrl": "https://www.vlr.gg/player/939/mwzera",
    "name": "mwzera",
    "kind": "photo"
  },
  "AM16": {
    "path": "assets/players/AM16.png",
    "profileUrl": "https://www.vlr.gg/player/8447/less",
    "name": "Less",
    "kind": "photo"
  },
  "AM17": {
    "path": "assets/players/AM17.png",
    "profileUrl": "https://www.vlr.gg/player/729/zellsis",
    "name": "Zellsis",
    "kind": "photo"
  },
  "AM18": {
    "path": "assets/players/AM18.png",
    "profileUrl": "https://www.vlr.gg/player/7873/leaf",
    "name": "leaf",
    "kind": "photo"
  },
  "EU01": {
    "path": "assets/players/EU01.png",
    "profileUrl": "https://www.vlr.gg/player/5022/derke",
    "name": "Derke",
    "kind": "photo"
  },
  "EU02": {
    "path": "assets/players/EU02.png",
    "profileUrl": "https://www.vlr.gg/player/9554/kaajak",
    "name": "kaajak",
    "kind": "photo"
  },
  "EU03": {
    "path": "assets/players/EU03.png",
    "profileUrl": "https://www.vlr.gg/player/21328/wo0t",
    "name": "Wo0t",
    "kind": "photo"
  },
  "EU04": {
    "path": "assets/players/EU04.png",
    "profileUrl": "https://www.vlr.gg/player/10307/marteen",
    "name": "marteen",
    "kind": "photo"
  },
  "EU05": {
    "path": "assets/players/EU05.png",
    "profileUrl": "https://www.vlr.gg/player/20144/lewn",
    "name": "LewN",
    "kind": "photo"
  },
  "EU06": {
    "path": "assets/players/EU06.png",
    "profileUrl": "https://www.vlr.gg/player/31305/lar0k",
    "name": "Lar0k",
    "kind": "photo"
  },
  "EU07": {
    "path": "assets/players/EU07.png",
    "profileUrl": "https://www.vlr.gg/player/9810/alfajer",
    "name": "Alfajer",
    "kind": "photo"
  },
  "EU08": {
    "path": "assets/players/EU08.png",
    "profileUrl": "https://www.vlr.gg/player/29873/benjyfishy",
    "name": "benjyfishy",
    "kind": "photo"
  },
  "EU09": {
    "path": "assets/players/EU09.png",
    "profileUrl": "https://www.vlr.gg/player/12795/crewen",
    "name": "Crewen",
    "kind": "photo"
  },
  "EU10": {
    "path": "assets/players/EU10.png",
    "profileUrl": "https://www.vlr.gg/player/438/boaster",
    "name": "Boaster",
    "kind": "photo"
  },
  "EU11": {
    "path": "assets/players/EU11.png",
    "profileUrl": "https://www.vlr.gg/player/18677/ruxic",
    "name": "Ruxic",
    "kind": "photo"
  },
  "EU12": {
    "path": "assets/players/EU12.png",
    "profileUrl": "https://www.vlr.gg/player/1144/boo",
    "name": "Boo",
    "kind": "photo"
  },
  "EU13": {
    "path": "assets/players/EU13.png",
    "profileUrl": "https://www.vlr.gg/player/4/crashies",
    "name": "crashies",
    "kind": "photo"
  },
  "EU14": {
    "path": "assets/players/EU14.png",
    "profileUrl": "https://www.vlr.gg/player/10971/riens",
    "name": "RieNs",
    "kind": "photo"
  },
  "EU15": {
    "path": "assets/players/EU15.png",
    "profileUrl": "https://www.vlr.gg/player/2168/trexx",
    "name": "trexx",
    "kind": "photo"
  },
  "EU16": {
    "path": "assets/players/EU16.png",
    "profileUrl": "https://www.vlr.gg/player/458/chronicle",
    "name": "Chronicle",
    "kind": "photo"
  },
  "EU17": {
    "path": "assets/players/EU17.png",
    "profileUrl": "https://www.vlr.gg/player/457/nats",
    "name": "nAts",
    "kind": "photo"
  },
  "EU18": {
    "path": "assets/players/EU18.png",
    "profileUrl": "https://www.vlr.gg/player/2858/suygetsu",
    "name": "SUYGETSU",
    "kind": "photo"
  },
  "PA01": {
    "path": "assets/players/PA01.png",
    "profileUrl": "https://www.vlr.gg/player/6672/meiy",
    "name": "Meiy",
    "kind": "photo"
  },
  "PA02": {
    "path": "assets/players/PA02.png",
    "profileUrl": "https://www.vlr.gg/player/28400/hyunmin",
    "name": "HYUNMIN",
    "kind": "photo"
  },
  "PA03": {
    "path": "assets/players/PA03.png",
    "profileUrl": "https://www.vlr.gg/player/24895/jemkin",
    "name": "Jemkin",
    "kind": "photo"
  },
  "PA04": {
    "path": "assets/players/PA04.png",
    "profileUrl": "https://www.vlr.gg/player/31827/dambi",
    "name": "Dambi",
    "kind": "photo"
  },
  "PA05": {
    "path": "assets/players/PA05.png",
    "profileUrl": "https://www.vlr.gg/player/13788/jitboys",
    "name": "JitBoyS",
    "kind": "photo"
  },
  "PA06": {
    "path": "assets/players/PA06.png",
    "profileUrl": "https://www.vlr.gg/player/46135/zeus",
    "name": "Zeus",
    "kind": "photo"
  },
  "PA07": {
    "path": "assets/players/PA07.png",
    "profileUrl": "https://www.vlr.gg/player/9196/t3xture",
    "name": "t3xture",
    "kind": "photo"
  },
  "PA08": {
    "path": "assets/players/PA08.png",
    "profileUrl": "https://www.vlr.gg/player/4871/xffero",
    "name": "xffero",
    "kind": "photo"
  },
  "PA09": {
    "path": "assets/players/PA09.png",
    "profileUrl": "https://www.vlr.gg/player/48925/raxcal",
    "name": "Raxcal",
    "kind": "photo"
  },
  "PA10": {
    "path": "assets/players/PA10.png",
    "profileUrl": "https://www.vlr.gg/player/4462/mako",
    "name": "MaKo",
    "kind": "photo"
  },
  "PA11": {
    "path": "assets/players/PA11.png",
    "profileUrl": "https://www.vlr.gg/player/34974/karon",
    "name": "Karon",
    "kind": "photo"
  },
  "PA12": {
    "path": "assets/players/PA12.png",
    "profileUrl": "https://www.vlr.gg/player/9801/f0rsaken",
    "name": "f0rsakeN",
    "kind": "photo"
  },
  "PA13": {
    "path": "assets/players/PA13.png",
    "profileUrl": "https://www.vlr.gg/player/8504/invy",
    "name": "invy",
    "kind": "photo"
  },
  "PA14": {
    "path": "assets/players/PA14.png",
    "profileUrl": "https://www.vlr.gg/player/4678/beyn",
    "name": "BeYN",
    "kind": "photo"
  },
  "PA15": {
    "path": "assets/players/PA15.png",
    "profileUrl": "https://www.vlr.gg/player/2489/munchkin",
    "name": "Munchkin",
    "kind": "photo"
  },
  "PA16": {
    "path": "assets/players/PA16.png",
    "profileUrl": "https://www.vlr.gg/player/7378/jinggg",
    "name": "Jinggg",
    "kind": "photo"
  },
  "PA17": {
    "path": "assets/players/PA17.png",
    "profileUrl": "https://www.vlr.gg/player/17086/something",
    "name": "something",
    "kind": "photo"
  },
  "PA18": {
    "path": "assets/players/PA18.png",
    "profileUrl": "https://www.vlr.gg/player/9803/d4v41",
    "name": "d4v41",
    "kind": "photo"
  }
};
export const ENEMY_ART={
  "A2_E01": {
    "path": "assets/opponents/rush.png",
    "name": "第二幕基础进攻",
    "archetype": "冲锋枪 · 快攻",
    "skinId": "rush",
    "skinName": "Singularity Spectre",
    "accent": "#9D4EDD"
  },
  "A2_E02": {
    "path": "assets/opponents/intel.png",
    "name": "第二幕信息压制",
    "archetype": "消音步枪 · 扫描",
    "skinId": "intel",
    "skinName": "Recon Phantom",
    "accent": "#00C2FF"
  },
  "A2_E03": {
    "path": "assets/opponents/twin.png",
    "name": "第二幕多段突击",
    "archetype": "双枪 · 连击",
    "skinId": "twin",
    "skinName": "Sensation Stinger",
    "accent": "#00FFAA"
  },
  "A2_E04": {
    "path": "assets/opponents/wall.png",
    "name": "第二幕防守反击",
    "archetype": "霰弹枪 · 壁垒",
    "skinId": "wall",
    "skinName": "Glitchpop Judge",
    "accent": "#FF00AA"
  },
  "A2_E05": {
    "path": "assets/opponents/control.png",
    "name": "第二幕纪律控制",
    "archetype": "重机枪 · 封锁",
    "skinId": "control",
    "skinName": "Glitchpop Odin",
    "accent": "#AA00FF"
  },
  "A2_EL01": {
    "path": "assets/opponents/elite.png",
    "name": "第二幕强敌",
    "archetype": "狙击枪 · 锁定",
    "skinId": "elite",
    "skinName": "Ion Operator",
    "accent": "#00D4FF"
  },
  "A2_B01": {
    "path": "assets/opponents/master2.png",
    "name": "第二次大师赛",
    "archetype": "幽紫能量 · 大师赛",
    "skinId": "master2",
    "skinName": "Reaver Operator",
    "accent": "#8B0000"
  },
  "A3_E01": {
    "path": "assets/opponents/rush.png",
    "name": "第三幕基础进攻",
    "archetype": "冲锋枪 · 快攻",
    "skinId": "rush",
    "skinName": "Singularity Spectre",
    "accent": "#9D4EDD"
  },
  "A3_E02": {
    "path": "assets/opponents/intel.png",
    "name": "第三幕信息压制",
    "archetype": "消音步枪 · 扫描",
    "skinId": "intel",
    "skinName": "Recon Phantom",
    "accent": "#00C2FF"
  },
  "A3_E03": {
    "path": "assets/opponents/twin.png",
    "name": "第三幕多段突击",
    "archetype": "双枪 · 连击",
    "skinId": "twin",
    "skinName": "Sensation Stinger",
    "accent": "#00FFAA"
  },
  "A3_E04": {
    "path": "assets/opponents/wall.png",
    "name": "第三幕防守反击",
    "archetype": "霰弹枪 · 壁垒",
    "skinId": "wall",
    "skinName": "Glitchpop Judge",
    "accent": "#FF00AA"
  },
  "A3_E05": {
    "path": "assets/opponents/control.png",
    "name": "第三幕纪律控制",
    "archetype": "重机枪 · 封锁",
    "skinId": "control",
    "skinName": "Glitchpop Odin",
    "accent": "#AA00FF"
  },
  "A3_EL01": {
    "path": "assets/opponents/elite.png",
    "name": "第三幕强敌",
    "archetype": "狙击枪 · 锁定",
    "skinId": "elite",
    "skinName": "Ion Operator",
    "accent": "#00D4FF"
  },
  "A3_B01": {
    "path": "assets/opponents/champion.png",
    "name": "冠军赛",
    "archetype": "龙焰 · 冠军赛",
    "skinId": "champion",
    "skinName": "Elderflame Vandal",
    "accent": "#FF4500"
  },
  "E01": {
    "path": "assets/opponents/rush.png",
    "name": "基础试训队",
    "archetype": "冲锋枪 · 快攻",
    "skinId": "rush",
    "skinName": "Singularity Spectre",
    "accent": "#9D4EDD"
  },
  "E02": {
    "path": "assets/opponents/intel.png",
    "name": "信息压制队",
    "archetype": "消音步枪 · 扫描",
    "skinId": "intel",
    "skinName": "Recon Phantom",
    "accent": "#00C2FF"
  },
  "E03": {
    "path": "assets/opponents/twin.png",
    "name": "双核突击队",
    "archetype": "双枪 · 连击",
    "skinId": "twin",
    "skinName": "Sensation Stinger",
    "accent": "#00FFAA"
  },
  "E04": {
    "path": "assets/opponents/wall.png",
    "name": "防守反击队",
    "archetype": "霰弹枪 · 壁垒",
    "skinId": "wall",
    "skinName": "Glitchpop Judge",
    "accent": "#FF00AA"
  },
  "E05": {
    "path": "assets/opponents/control.png",
    "name": "纪律控制队",
    "archetype": "重机枪 · 封锁",
    "skinId": "control",
    "skinName": "Glitchpop Odin",
    "accent": "#AA00FF"
  },
  "EL01": {
    "path": "assets/opponents/elite.png",
    "name": "高压强敌队",
    "archetype": "狙击枪 · 锁定",
    "skinId": "elite",
    "skinName": "Ion Operator",
    "accent": "#00D4FF"
  },
  "B01": {
    "path": "assets/opponents/master1.png",
    "name": "大师赛种子队",
    "archetype": "金白晶体 · 大师赛",
    "skinId": "master1",
    "skinName": "Prime Vandal",
    "accent": "#FFD700"
  }
};
