// Tiny dependency-free packer for this project's named ES-module exports.
// Supports aliases in named imports (import { act as baseAct }).
import { readFile, writeFile } from 'node:fs/promises';
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import './build-art.mjs';

const root = new URL('../', import.meta.url);
const read = f => readFile(new URL(f, root), 'utf8');
const modules = [
  'regions.js',
  'regional-expansion.js',
  'afflictions.js',
  'shared-route-generator.js',
  'shared-unknown-room.js',
  'shared-event-core.js',
  'season-map.js',
  'content.js',
  'wa-rules.js',
  'card-rarity.js',
  'wa-events.js',
  'engine.js',
  'navigation.js',
  'art-data.js',
  'weapon-frame.js',
  'art-ui.js',
  'combat-events.js',
  'shared/sfx.js',
  'shared/juice.js',
  'wa-juice.js',
  'combat-fx.js',
  'wa-season.js',
  'wa-online.js',
  'shared/card-pile-motion.js',
  'shared/status-icons.js',
  'shared/touch-feel.js',
  'ui-source.js'
];

const symbols = new Map(modules.map((file, i) => [file, `module${i}`]));
const output = ['// Generated by tools/build-browser.mjs. Edit source modules, then npm run build.'];

for (const file of modules) {
  let source = await read(file);
  const exports = [];

  // Transform local named imports, supporting aliases: import { act as baseAct } from './x.js' -> const { act: baseAct } = moduleX;
  source = source.replace(/import\s*\{([^}]+)\}\s*from\s*['"]\.\/([^'"]+)['"];?/g, (_, names, target) => {
    if (!symbols.has(target)) throw Error(`Unknown module ${target}`);
    const cleaned = names.trim().split(',').map(part => {
      const [orig, alias] = part.trim().split(/\s+as\s+/);
      return alias ? `${orig.trim()}:${alias.trim()}` : part.trim();
    }).join(', ');
    return `const { ${cleaned} } = ${symbols.get(target)};`;
  });

  // Collect exports from const/function/async function declarations and export lists.
  source = source.replace(/export\s+(const|function|async\s+function)\s+([A-Za-z_$][\w$]*)/g, (_, kind, name) => {
    exports.push(name);
    return `${kind} ${name}`;
  });
  source = source.replace(/export\s*\{([^}]+)\};?/g, (_, names) => {
    exports.push(...names.split(',').map(x => x.trim().split(/\s+as\s+/)[0]));
    return '';
  });

  if (/^\s*(?:import|export)\b/m.test(source)) throw Error(`Unsupported module syntax in ${file}`);

  output.push(`const ${symbols.get(file)}=(()=>{\n${source}\nreturn {${[...new Set(exports)].join(',')}};\n})();`);
}

await writeFile(new URL('app.js', root), output.join('\n'));
await writeFile(new URL('style.css', root),
  (await read('base-style.css')) + '\n' + (await read('season-ui.css')) + '\n' + (await read('weapon-style.css')) + '\n' + (await read('art-style.css')) + '\n' + (await read('combat-fx.css')) + '\n' + (await read('cover-wa.css')) + '\n' + (await read('wa-map-redesign.css')) + '\n' + (await read('shared/character-stage.css')) + '\n' + (await read('shared/status-icons.css')) + '\n' + (await read('shared/shop-scene.css')) + '\n' + (await read('shared/juice.css')) + '\n' + (await read('wa-rooms.css')) + '\n' + (await read('wa-rules.css'))
  // Phone feel (long-press sheet, drag hint, touch targets) goes last so it wins.
  + '\n' + (await read('shared/touch-feel.css')) + '\n' + (await read('wa-phone.css'))
);
await build({ entryPoints: [fileURLToPath(new URL('shared/character-stage-source.js', root))], bundle: true, format: 'esm', platform: 'browser', outfile: fileURLToPath(new URL('character-stage.js', root)), minify: true, target: 'es2020' });
console.log('Browser assets built.');
