// Tiny dependency-free packer for this project's named ES-module exports.
// The live preview can load the update without restarting its static server.
import {readFile,writeFile} from 'node:fs/promises';
const root=new URL('../',import.meta.url),read=f=>readFile(new URL(f,root),'utf8');
const modules=['regions.js','season-map.js','content.js','engine.js','navigation.js','ui-source.js'];
const symbols=new Map(modules.map((file,i)=>[file,`module${i}`]));
const output=['// Generated by tools/build-browser.mjs. Edit ui-source.js or the rule modules, then npm run build.'];
for(const file of modules){
 let source=await read(file);const exports=[];
 source=source.replace(/import\s*\{([^}]+)\}\s*from\s*['"]\.\/([^'"]+)['"];?/g,(_,names,target)=>{if(!symbols.has(target))throw Error(`Unknown module ${target}`);return `const {${names}}=${symbols.get(target)};`;});
 source=source.replace(/export\s+(const|function)\s+(\w+)/g,(_,kind,name)=>{exports.push(name);return `${kind} ${name}`;});
 source=source.replace(/export\s*\{([^}]+)\};?/g,(_,names)=>{exports.push(...names.split(',').map(x=>x.trim()));return '';});
 if(/^\s*(?:import|export)\b/m.test(source))throw Error(`Unsupported module syntax in ${file}`);
 output.push(`const ${symbols.get(file)}=(()=>{\n${source}\nreturn {${exports.join(',')}};\n})();`);
}
await writeFile(new URL('app.js',root),output.join('\n'));
await writeFile(new URL('style.css',root),(await read('base-style.css'))+'\n'+(await read('season-ui.css')));
console.log('Browser assets built.');
